### ISSUE TITLE
about AD modify issues

### ISSUE THREAD

**Issue by qiwenha** [LeoBest2/ADPassword#1]
Hi Leo
https://blog.csdn.net/LeoForBest/article/details/80384559，简易版网页问题。
想获取两个帮助，感激不尽：1.如何把前端二维码添加上，和js做验证码校验后再做账户密码验证
2.用户密码过期时无法检索到用户信息。如何用户提交完账号密码后，在auth.py添加先seacherDN动作，并做useraccountcontrol544动作。让系统能识别上去过期passwd

Cheers
Wenhao

**Comment by LeoBest2** [comment]
你好：
1.  第一个问题是指添加图片验证码防止爆破么？如果是，建议在域控上做`账户锁定策略`,在一定时间内登陆失败多少次则锁定一段时间。
2. 用户密码过期后通过LDAP绑定应该是会失败的，可以用预置账号检索该用户的`PasswordLastSet`属性，使用`当前时间` - `PasswordLastSet` = `时间差`，大于`域策略的密码最长使用时间`，则提示用户密码已过期，这个方法应该可行。如有更好的方法欢迎指教。

**Comment by LeoBest2** [comment]
> Hi Leo
> [https://blog.csdn.net/LeoForBest/article/details/80384559，简易版网页问题。](https://blog.csdn.net/LeoForBest/article/details/80384559%EF%BC%8C%E7%AE%80%E6%98%93%E7%89%88%E7%BD%91%E9%A1%B5%E9%97%AE%E9%A2%98%E3%80%82)
> 想获取两个帮助，感激不尽：1.如何把前端二维码添加上，和js做验证码校验后再做账户密码验证
> 2.用户密码过期时无法检索到用户信息。如何用户提交完账号密码后，在auth.py添加先seacherDN动作，并做useraccountcontrol544动作。让系统能识别上去过期passwd
> 
> Cheers
> Wenhao
你好：

第一个问题是指添加图片验证码防止爆破么？如果是，建议在域控上做账户锁定策略,在一定时间内登陆失败多少次则锁定一段时间。
用户密码过期后通过LDAP绑定应该是会失败的，可以用预置账号检索该用户的PasswordLastSet属性，使用当前时间 - PasswordLastSet = 时间差，大于域策略的密码最长使用时间，则提示用户密码已过期，这个方法应该可行。如有更好的方法欢迎指教。

**Comment by LeoBest2** [comment]
> Hi Leo
> [https://blog.csdn.net/LeoForBest/article/details/80384559，简易版网页问题。](https://blog.csdn.net/LeoForBest/article/details/80384559%EF%BC%8C%E7%AE%80%E6%98%93%E7%89%88%E7%BD%91%E9%A1%B5%E9%97%AE%E9%A2%98%E3%80%82)
> 想获取两个帮助，感激不尽：1.如何把前端二维码添加上，和js做验证码校验后再做账户密码验证
> 2.用户密码过期时无法检索到用户信息。如何用户提交完账号密码后，在auth.py添加先seacherDN动作，并做useraccountcontrol544动作。让系统能识别上去过期passwd
> 
> Cheers
> Wenhao

你好：
1.  第一个问题是指添加图片验证码防止爆破么？如果是，建议在域控上做`账户锁定策略`,在一定时间内登陆失败多少次则锁定一段时间。
2. 用户密码过期后通过LDAP绑定应该是会失败的，可以用预置账号检索该用户的`PasswordLastSet`属性，使用`当前时间` - `PasswordLastSet` = `时间差`，大于`域策略的密码最长使用时间`，则提示用户密码已过期，这个方法应该可行。如有更好的方法欢迎指教。
